name: Release

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: false
        default: '1.0.0'

permissions:
  contents: write

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version from main_addon.py
        id: extract_version
        run: |
          # Extract version number from line 4 of main_addon.py
          version=$(grep -oP '(?<=version": \()[0-9]+,[0-9]+,[0-9]+' main_addon.py | tr -d '(),' | sed 's/,/./g')
          echo "VERSION=${version}" >> $GITHUB_ENV

      - name: Build addon
        uses: blenderkit/blender-addon-build@main
        with:
          name: PhantomEngineAddon
          exclude-files: ".git;.github;README.md"

      - name: Create zip file
        run: |
          zip -r PhantomEngineAddon_v${{ env.VERSION }}.zip main_addon.py

  Release:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create tag
        id: create_tag
        run: |
          git tag -a "v${{ env.VERSION }}" -m "Release version ${{ env.VERSION }}"
          git push origin "v${{ env.VERSION }}"

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: PhantomEngineAddon_v${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: PhantomEngineAddon_v${{ env.VERSION }}.zip
          asset_name: PhantomEngineAddon_v${{ env.VERSION }}.zip
          asset_content_type: application/zip

