name: Build Blender Addon
uses: blenderkit/blender-addon-build@main
with:
    name: 'PhantomEngineAddon'
    name-suffix: 'commit-hash'
    build-command: 'make build'
    build-location: './build'
    do-checkout: 'true'
    exclude-files: '.git;.github;.gitignore'
