name: Release

on:
  push:
    branches: [ '**' ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: false
        default: '1.0.0'

permissions:
  contents: write

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version from main_addon.py
        id: extract_version
        run: |
          # Extract version number from line 4 of main_addon.py
          version=$(sed -n "4p" main_addon.py | sed "s/^version = '\(.*\)'.*/\1/")
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Build addon
        uses: blenderkit/blender-addon-build@main
        with:
          name: PhantomEngineAddon
          exclude-files: ".git;.github;README.md"

  Release:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Release addon
        uses: blenderkit/blender-addon-release@main
        with:
          release_name: PhantomEngineAddon
          version: ${{ env.VERSION }}

