name: Release

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: '1.0.0'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version from main_addon.py
        id: extract_version
        run: |
          version=$(grep -oP '(?<=version": \()[0-9]+,[0-9]+,[0-9]+' main_addon.py | tr -d '(),' | sed 's/,/./g')
          echo "VERSION=${version}" >> $GITHUB_ENV

      - name: Build addon
        uses: blenderkit/blender-addon-build@main
        with:
          name: PhantomEngineAddon
          exclude-files: ".git;.github;README.md"

      - name: Create zip file
        run: |
          zip -r PhantomEngineAddon_v${{ env.VERSION }}.zip .

      - name: Create tag
        run: |
          git tag -a "v${{ env.VERSION }}" -m "Release version ${{ env.VERSION }}"
          git push origin "v${{ env.VERSION }}"

      - name: Create Release
        id: create_release
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"tag_name\": \"v${{ env.VERSION }}\", \"name\": \"PhantomEngineAddon v${{ env.VERSION }}\", \"body\": \"Release version ${{ env.VERSION }}\", \"draft\": false, \"prerelease\": false}" \
            https://api.github.com/repos/${{ github.repository }}/releases

      - name: Upload release asset
        run: |
          release_id=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/releases | jq -r '.[] | select(.tag_name == "v${{ env.VERSION }}") | .id')

          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/zip" \
            --data-binary @PhantomEngineAddon_v${{ env.VERSION }}.zip \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/${release_id}/assets?name=PhantomEngineAddon_v${{ env.VERSION }}.zip"

